config/routes.rb
Rails.application.routes.draw do
  root to: 'homepage#index'
  resources :users, except: [:new]
  delete 'session_logout', to: 'session#logout'
  post 'session_login', to: 'session#login'
  mount ActionCable.server => '/cable'

  namespace :admin do
    get 'bibliophile_admin', to: 'bibliophile_admin#index'
    patch 'bibliophile_admin_user_update', to: 'bibliophile_admin#user_update'
  end

  resources :books

  resources :events, except: [:index, :show]

  resources :posts, only: [:destroy]

  get 'about', to: 'about#index'

  get 'message_board', to: 'message_board#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author , presence: true
  validates :description , presence: true

  enum status: [:read, :reading]

  has_one_attached :photo
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true
  belongs_to :user

  def create_date
    created_at.strftime('%A %b %w, %Y %l:%M')
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :message
  belongs_to :user

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def create_date
    created_at.strftime('%A %b %e %Y %l:%M')
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :bio, presence: true
  validates :email, presence: true, uniqueness: true

  enum auth_type: [:user, :admin, :visitor]

  has_secure_password

  has_many :posts, :dependent => :delete_all
  has_one_attached :photo, :dependent => :delete_all

  include Rails.application.routes.url_helpers

  def photo_url
    rails_blob_path(photo, disposition: "attachment", only_path: true)
  end

  def last_twenty_posts
    self.posts.order(created_at: :desc).limit(20)
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @books = Book.includes(photo_attachment: [:blob]).all
  end
end

app/controllers/admin/bibliophile_admin_controller.rb
class Admin::BibliophileAdminController < ApplicationController
  before_action :admin_check
  def index
    @users = User.all
    @book  = Book.new
    @books = Book.includes(photo_attachment: [:blob]).all
    @event = Event.new
    @events = Event.all
  end

  def user_update
    if user = User.find(user_params[:id])
      user.update(user_params)
      redirect_to admin_bibliophile_admin_path
    else
      render :file => 'public/404.html', :status => :not_found, :layout => false
    end
  end

  private

  def admin_check
    unless current_user && current_user.admin?
      render :file => 'public/404.html', :status => :not_found, :layout => false
    end
  end

  def user_params
    params.require(:user).permit(:id, :auth_type)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    if book = Book.create(book_params)
      redirect_to admin_bibliophile_admin_path
    else
      redirect_to admin_bibliophile_admin_path
    end
  end

  def update
    if book = Book.find(params[:id]).update(book_params)
      redirect_to admin_bibliophile_admin_path
    else
      render :file => 'public/500.html', :status => :not_found, :layout => false
    end
  end

  def destroy
    Book.destroy(params[:id])
    redirect_to admin_bibliophile_admin_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :description, :photo, :status, :id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :check_status

  def create
    if event = Event.create(event_params)
      redirect_to admin_bibliophile_admin_path
    else
      render :file => 'public/500.html', :status => :not_found, :layout => false
    end
  end

  def destroy
    Event.delete(params[:id])
    redirect_to admin_bibliophile_admin_path
  end

  private

  def check_status
    unless current_user && current_user.admin?
      render :file => 'public/500.html', :status => :not_found, :layout => false
    end
  end

  def event_params
    params.require(:event).permit(:message)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @user  = User.new
    @book = Book.where(:status => 'reading')
    @books = Book.includes(photo_attachment: [:blob]).all
  end
end

app/controllers/message_board_controller.rb
class MessageBoardController < ApplicationController
  def index
    @posts = Post.includes(user: [photo_attachment: [:blob]]).order(created_at: :desc).limit(100).reverse
    @post  = Post.new
    @events = Event.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def destroy
    current_user.posts.destroy(params[:id])
    redirect_to user_path(current_user)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def login
    user = User.find_by(username: login_params[:username])
    if user && user.authenticate(login_params[:password])
      session[:user_id] = user.id
      cookies.encrypted[:user_id] = user.id
      redirect_to root_path
    else
      flash[:login_error] = 'You Entered the wrong username or password'
      redirect_to root_path
    end
  end

  def logout
    session[:user_id] = nil
    cookies.encrypted[:user_id] = nil
    redirect_to root_path
  end

  private
  def login_params
    params.permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if user = User.find(params[:id])
      if user == current_user
        redirect_to edit_user_path
      end
      @user = user
    else
      flash[:user_failure] = 'You have entered an invalid user id.'
      redirect_to root_path
    end
  end

  def create
    user = User.new(user_params)
    if user_params[:photo] == nil
      user.photo.attach(io: File.open('./app/assets/images/booknerd.jpg'), filename: 'booknerd.jpg', content_type: 'image/jpg')
    end
    if user.save
      session[:user_id] = user.id
      cookies.encrypted[:user_id] = user.id
      redirect_to root_path
    else
      flash[:failure] = 'You must have entered something wrong. Please try again.'
      redirect_to root_path
    end
  end

  def edit
    @user = current_user
  end

  def update
    current_user.update(user_params)
    redirect_to user_path
  end

  def destroy
    User.destroy(params[:id])
    redirect_to admin_bibliophile_admin_path
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :password, :email, :bio, :photo, :auth_type )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/about/index.html.erb
<div id='navbar'>
  <p id='welcome'> About The Mile High Bibliophiles </p>
  <p id='homepage_link'>Back to the <%= link_to "homepage", root_path %></p>
</div>
<div id='about'>
  <p id='about_message'>Meetings are typically bi-weekly, on Fridays at 7 or 7:30pm. Never joined a book club before? Not to worry!<br>Come on down, we'd love to have you!</p>
</div>
<div id='read_books_grid'>
  <p id='read_books_header'>Books We've Read</p>
  <% @books.each do |book| %>
    <%= image_tag(book.photo, id:'about_photo_of_book', alt:'book_photo') %>
  <% end %>
</div>

app/views/admin/bibliophile_admin/_books.html.erb
<div id='books_admin'>
  <div id='new_book_admin'>
    <%= form_for @book, multipart: true do |f| %>
      <%= content_tag(:p, "Enter A New Book") %>
      <%= f.label(:title, 'Book Title', id: 'label_admin') %>
      <%= f.text_field(:title, class: 'field_admin') %>
      <%= f.label(:author, 'Book Author', id: 'label_admin') %>
      <%= f.text_field(:author, class: 'field_admin') %>
      <%= f.label(:description, 'Add a Description', id: 'label_admin') %><br>
      <%= f.text_area(:description, class: 'field_admin') %><br>
      <%= f.label(:photo, 'Add a Photo', id: 'label_admin') %>
      <%= f.file_field(:photo, class: 'field_admin') %>
      <%= f.select('status', Book.statuses.collect {|key, val| [key]}) %><br>
      <%= f.submit %>
    <% end %>
  </div>
  <p>Edit Previous Books</p>
  <div id='all_mhb_books'>
    <% @books.each do |book| %>
      <%= form_for book, :html => { :multipart => true } do |f| %>
      <%= f.label(:title, 'Book Title', id: 'label_admin') %>
      <%= f.text_field(:title, id: 'field_admin') %><br>
      <%= f.label(:author, 'Book Author', id: 'label_admin') %>
      <%= f.text_field(:author, id: 'field_admin') %><br>
      <%= f.label(:description, 'Add a Description', id: 'label_admin') %><br>
      <%= f.text_area(:description, id: 'field_admin') %><br>
      <%= content_tag(:p, "Current Photo") %>
      <%= image_tag(book.photo, id:'admin_photo_of_book', alt:'book_photo') %><br>
      <%= f.label(:photo, 'Change Photo', id: 'label_admin') %><br>
      <%= f.file_field(:photo, id: 'field_admin') %><br>
      <%= f.select('status', Book.statuses.collect {|key, val| [key]}) %><br>
      <%= f.submit %>
      <% end %>
      <%= form_for book, :html => {class: 'delete_book_admin'}, method: :delete do |f| %>
        <%= f.submit('Delete Book') %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/admin/bibliophile_admin/_events.html.erb
<div id='admin_events'>
  <div id='new_event_admin'>
    <%= form_for @event do |f| %>
    <%= content_tag(:p, "Enter An Event Message") %>
    <%= f.text_area(:message, class: 'event_message_admin') %>
    <%= f.submit %>
    <% end %>
  </div>
  <% if @events.empty? %>
    <%= content_tag(:p, "There are no current events posted.") %>
  <% else %>
    <% @events.each do |event| %>
      <%= form_for event, method: :delete do |f| %>
        <%= content_tag(:p, "#{event.message}") %>
        <%= f.submit("Delete Message") %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/admin/bibliophile_admin/_users.html.erb
<div id='users'>
  <% @users.each do |user| %>
    <%= form_for user, url: admin_bibliophile_admin_user_update_path do |f| %>
      <%= content_tag(:p, "#{user.first_name} #{user.last_name}") %>
      <%= content_tag(:p, "#{user.auth_type}") %>
      <%= content_tag(:p, "#{user.email}") %>
      <%= f.hidden_field('id') %>
      <%= f.select('auth_type', User.auth_types.collect {|key, val| [key]}) %>
      <%= f.submit("Create Admin") %>
    <% end %>
    <%= form_for user, :html => {class: 'delete_user_admin'}, method: :delete do |f| %>
      <%= f.submit("Delete User") %>
    <% end %>
  <% end %>
</div>

app/views/admin/bibliophile_admin/index.html.erb
<div id='navbar'>
  <p id='welcome'> Welcome Admin </p>
  <p id='homepage_link'>Back to the <%= link_to "homepage", root_path %></p>
</div>
<div id='admin_body'>
  <%= render partial: 'users' %>
  <%= render partial: 'books' %>
  <%= render partial: 'events' %>
</div>

app/views/homepage/_header.html.erb
<div id='header'>
  <div id='header_mhb'>Mile High Bibliophiles</div>
</div>

app/views/homepage/_homepage_body.html.erb
<body id='homepage_body'>
  <div id='about'>
    <p id='home_about_message'>Mile High Bibliophiles is a book club unlike other book clubs.  We are a book club of diversity, inclusivity and warmth.  We choose each book by vote - every member bringing their own pick and pitching it to the group.  We strive to move thoughtfully and slowly through each of our reads, so as to allow a full bloom of conversation to develop.  We are a group of friends and a community who value a little drink, a little food and a lot of fun and reading.</p>
  </div>
  <div id='current_book'>
    <div id='book_header'>Our Current Book Is</div>
    <% @book.each do |book| %>
      <div id='book_photo'>
        <%= image_tag(book.photo, id:'photo_of_book', alt:'book_photo') %>
      </div>
    <% end %>
  </div>
  <div id='about'>
    <p id='about_message'>Meetings are typically bi-weekly, on Fridays at 7 or 7:30pm. Never joined a book club before? Not to worry!<br>Come on down, we'd love to have you!</p>
  </div>
  <div id='read_books_grid'>
    <p id='read_books_header'>Books We've Read</p>
    <% @books.each do |book| %>
      <%= image_tag(book.photo, id:'about_photo_of_book', alt:'book_photo') %>
    <% end %>
  </div>
</body>

app/views/homepage/_log_in.html.erb
<div id='log_in_modal'>
  <div id='log_in_form'>
    <p id='log_in_close'>&times;</p>
    <p id='log_in_message'>ENTER YOUR USERNAME AND PASSWORD</p>
    <%= form_tag(session_login_path) do %>
      <%= label_tag(:username, 'User Name', id: 'label') %><br>
      <%= text_field_tag(:username, "", class: 'field') %><br>
      <%= label_tag(:password, 'Password', id: 'label') %><br>
      <%= password_field_tag(:password, "", class: 'field') %><br>
      <%= submit_tag("Log In Bibliophile!", class: 'submit_btn') %>
    <% end %>
  </div>
</div>

app/views/homepage/_nav_bar.html.erb
<div id='navbar'>
  <% if flash[:failure] %>
  <p id='flash1'><%= flash[:failure] %></p>
  <button id='sign_up'>Sign Up</button>
  <button id='log_in'>Log In</button>
  <%= link_to 'Discussion', message_board_path, form_class: 'message-board', id: 'message-board' %>
  <% elsif flash[:login_error] %>
  <p id='flash2'><%= flash[:login_error] %></p>
  <button id='sign_up'>Sign Up</button>
  <button id='log_in'>Log In</button>
  <%= link_to 'Discussion', message_board_path, form_class: 'message-board', id: 'message-board' %>
  <% elsif current_user && current_user.admin? %>
  <p id='welcome'> Welcome <%= current_user.first_name %> <%= current_user.last_name %></p>
  <%= button_to 'administration', admin_bibliophile_admin_path, method: 'get', form_class: 'admin_link', id: 'admin_link' %>
  <%= button_to 'Log Out', session_logout_path, method: 'delete', form_class: 'log_out', id: 'log_out'%>
  <%= link_to 'Discussion', message_board_path, form_class: 'message-board', id: 'message-board' %>
  <% elsif current_user %>
  <p id='welcome'> Welcome <%= current_user.first_name %> <%= current_user.last_name %></p>
  <%= button_to 'Log Out', session_logout_path, method: 'delete', form_class: 'log_out', id: 'log_out'%>
  <%= link_to 'Discussion', message_board_path, form_class: 'message-board', id: 'message-board' %>
  <% else %>
  <p id='welcome'>Welcome, please sign in or sign up!</p>
  <button id='sign_up'>Sign Up</button>
  <button id='log_in'>Log In</button>
  <%= link_to 'Discussion', message_board_path, form_class: 'message-board', id: 'message-board' %>
  <% end %>
</div>

app/views/homepage/_sign_up.html.erb
<div id='sign_up_modal'>
  <div id='sign_up_form'>
    <p id='sign_up_close'>&times;</p>
    <p id='sign_up_message'>SIGN UP FOR MILE HIGH BIBLIOPHILES</p>
    <%= form_for @user, multipart: true do |f| %>
      <%= f.label(:first_name, 'First Name', id: 'label') %><br>
      <%= f.text_field(:first_name, class: 'field') %><br>
      <%= f.label(:last_name, 'Last Name', id: 'label') %><br>
      <%= f.text_field(:last_name, class: 'field') %><br>
      <%= f.label(:username, 'Username', id: 'label') %><br>
      <%= f.text_field(:username, class: 'field') %><br>
      <%= f.label(:password, 'Password', id: 'label') %><br>
      <%= f.password_field(:password, class: 'field') %><br>
      <%= f.label(:email, 'Email', id: 'label') %><br>
      <%= f.email_field(:email, class: 'field') %><br>
      <%= f.label(:bio, 'Bio', id: 'label') %><br>
      <%= f.text_area(:bio, class: 'field') %><br>
      <%= f.label(:photo, 'Upload a Photo', id: 'label') %><br>
      <%= f.file_field(:photo, class: 'field') %><br>
      <%= f.submit("Become A Bibliophile!", class: 'submit_btn') %>
    <% end %>
  </div>
</div>

app/views/homepage/index.html.erb
<%= render partial: 'header' %>
<%= render partial: 'nav_bar' %>
<%= render partial: 'sign_up' %>
<%= render partial: 'log_in' %>
<%= render partial: 'homepage_body' %>
<footer>
</footer>
<%= javascript_include_tag 'root_page.js' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8' />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MileHighBibliofiles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Shrikhand|Libre+Baskerville|Permanent+Marker|Poppins:500|Ubuntu:300|Nunito:900" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/message_board/index.html.erb
<div id='navbar'>
  <p id='welcome'>THIS IS THE MHB MESSAGE BOARD</p>
  <p id='homepage_link'>Back to the <%= link_to "homepage", root_path %></p>
</div>
<div id='message_grid'>
  <div id='upcoming_events'>
    <div id='events_header'>
      <p>Upcoming Events:</p>
    </div>
    <div id='upcomming_events_body'>
      <div id='events_body'>
        <% if @events.empty? %>
        <%= content_tag(:p, "> There are no current events posted.") %>
        <% else %>
        <% @events.each do |event| %>
        <%= content_tag(:p, "> #{event.message}") %>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div id='message_header'>
    <p id='mhb_message_board'>MHB POSTS</p>
  </div>
  <div id='message_board'>
    <% @posts.each do |message| %>
      <%= image_tag(message.user.photo, id:'message_photo', alt:'user_photo', height:'50', width:'50') %>
      <%= tag.div id: 'message_text' do %>
        <%= link_to("#{message.user.username}", user_path(message.user), id:'message_name') %>
        <%= content_tag(:span, "#{message.create_date}", id:'message_date') %>
        <%= content_tag(:p, "#{message.message}", id:'message_message') %>
      <% end %>
    <% end %>
  </div>
  <% if current_user %>
    <%= form_for @post, url: '#' do |f| %>
      <%= f.submit 'Add Message', id: 'add_message_btn' %>
      <%= f.text_area :message %>
    <% end %>
  <% end %>
</div>
<%= javascript_include_tag 'cable.js' %>

app/views/users/edit.html.erb
<div id='navbar'>
  <% if current_user %>
  <p id='welcome'> Welcome <%= current_user.first_name %> <%= current_user.last_name %></p>
  <p id='homepage_link'>Back to the <%= link_to "homepage", root_path %> or <%= link_to "Discussion", message_board_path %></p>
  <% else %>
  <p id='welcome'>Welcome, Go to the <%= link_to "homepage", root_path %> to sign in or sign up!</p>
  <% end %>
</div>
<body id='profile_body'>
  <header id=profile_header>
    HERE YOU CAN EDIT YOUR INFORMATION
  </header>
  <%= form_for @user, :html => { :multipart => true } do |f| %>
  <div id='profile_information'>
    <div id='profile_photo_div'>
      <%= image_tag(@user.photo, id:'profile_photo', alt:'profile_photo') %>
    </div>
    <div id='user_text'>
      User Name: <%= f.text_field :username %><br>
      Email: <%= f.email_field :email  %><br>
      Bio: <%= f.text_area :bio %><br>
      Pic: <%= f.file_field(:photo, class: 'field') %><br>
      <%= f.submit("Update You Profile", class: 'submit_btn') %>
    </div>
  <% end %>
  <div id='user_messages'>
    <p id='user_messages_header'>Here Are Your Last 20 Posts:</p>
    <% @user.last_twenty_posts.each do |post| %>
    <%= form_for post, method: :delete do |f| %>
    <%= content_tag(:p, "#{post.message}") %>
    <%= f.submit("Delete Message") %>
    <% end %>
    <% end %>
  </div>
</div>
</body>

app/views/users/show.html.erb
<div id='navbar'>
  <% if current_user %>
  <p id='welcome'> Welcome <%= current_user.first_name %> <%= current_user.last_name %></p>
  <p id='homepage_link'>Back to the <%= link_to "homepage", root_path %> or <%= link_to "Discussion", message_board_path %></p>
  <% else %>
  <p id='welcome'>Welcome, Go to the <%= link_to "homepage", root_path %> to sign in or sign up!</p>
  <% end %>
</div>
<body id='profile_body'>
  <header id=profile_header>
    MHB Profile for: <%= @user.first_name %> <%= @user.last_name %>
  </header>
  <div id='profile_information'>
    <div id='profile_photo_div'>
      <%= image_tag(@user.photo, id:'profile_photo', alt:'profile_photo') %>
    </div>
    <div id='user_text'>
      User Name: <%= @user.username %><br>
      Email: <%= @user.email %><br>
      Bio: <%= @user.bio %>
    </div>
  </div>
</body>